[
    {
        dailyKcal: 49,
        dailyPortion: 0.125,
        key: 'instant:cup:0.125',
        productLine: 'instant',
        servingSize: 'cup',
    },
    {
        dailyKcal: 73,
        dailyPortion: 0.1875,
        key: 'instant:cup:0.1875',
        productLine: 'instant',
        servingSize: 'cup',
    },
    {
        dailyKcal: 98,
        dailyPortion: 0.25,
        key: 'instant:cup:0.25',
        productLine: 'instant',
        servingSize: 'cup',
    },
    {
        dailyKcal: 130,
        dailyPortion: 0.3333,
        key: 'instant:cup:0.3333',
        productLine: 'instant',
        servingSize: 'cup',
    },
    {
        dailyKcal: 146,
        dailyPortion: 0.375,
        key: 'instant:cup:0.375',
        productLine: 'instant',
        servingSize: 'cup',
    },
    {
        dailyKcal: 171,
        dailyPortion: 0.4375,
        key: 'instant:cup:0.4375',
        productLine: 'instant',
        servingSize: 'cup',
    },
    {
        dailyKcal: 195,
        dailyPortion: 0.5,
        key: 'instant:cup:0.5',
        productLine: 'instant',
        servingSize: 'cup',
    },
    {
        dailyKcal: 219,
        dailyPortion: 0.5625,
        key: 'instant:cup:0.5625',
        productLine: 'instant',
        servingSize: 'cup',
    },
    {
        dailyKcal: 260,
        dailyPortion: 0.6667,
        key: 'instant:cup:0.6667',
        productLine: 'instant',
        servingSize: 'cup',
    },
    {
        dailyKcal: 293,
        dailyPortion: 0.75,
        key: 'instant:cup:0.75',
        productLine: 'instant',
        servingSize: 'cup',
    },
    {
        dailyKcal: 341,
        dailyPortion: 0.875,
        key: 'instant:cup:0.875',
        productLine: 'instant',
        servingSize: 'cup',
    },
    {
        dailyKcal: 390,
        dailyPortion: 1,
        key: 'instant:cup:1',
        productLine: 'instant',
        servingSize: 'cup',
    },
    {
        dailyKcal: 439,
        dailyPortion: 1.125,
        key: 'instant:cup:1.125',
        productLine: 'instant',
        servingSize: 'cup',
    },
    {
        dailyKcal: 488,
        dailyPortion: 1.25,
        key: 'instant:cup:1.25',
        productLine: 'instant',
        servingSize: 'cup',
    },
    {
        dailyKcal: 520,
        dailyPortion: 1.3333,
        key: 'instant:cup:1.3333',
        productLine: 'instant',
        servingSize: 'cup',
    },
    {
        dailyKcal: 585,
        dailyPortion: 1.5,
        key: 'instant:cup:1.5',
        productLine: 'instant',
        servingSize: 'cup',
    },
    {
        dailyKcal: 650,
        dailyPortion: 1.6667,
        key: 'instant:cup:1.6667',
        productLine: 'instant',
        servingSize: 'cup',
    },
    {
        dailyKcal: 683,
        dailyPortion: 1.75,
        key: 'instant:cup:1.75',
        productLine: 'instant',
        servingSize: 'cup',
    },
    {
        dailyKcal: 780,
        dailyPortion: 2,
        key: 'instant:cup:2',
        productLine: 'instant',
        servingSize: 'cup',
    },
    {
        dailyKcal: 878,
        dailyPortion: 2.25,
        key: 'instant:cup:2.25',
        productLine: 'instant',
        servingSize: 'cup',
    },
    {
        dailyKcal: 910,
        dailyPortion: 2.3333,
        key: 'instant:cup:2.3333',
        productLine: 'instant',
        servingSize: 'cup',
    },
    {
        dailyKcal: 975,
        dailyPortion: 2.5,
        key: 'instant:cup:2.5',
        productLine: 'instant',
        servingSize: 'cup',
    },
    {
        dailyKcal: 1040,
        dailyPortion: 2.6667,
        key: 'instant:cup:2.6667',
        productLine: 'instant',
        servingSize: 'cup',
    },
    {
        dailyKcal: 1073,
        dailyPortion: 2.75,
        key: 'instant:cup:2.75',
        productLine: 'instant',
        servingSize: 'cup',
    },
    {
        dailyKcal: 1170,
        dailyPortion: 3,
        key: 'instant:cup:3',
        productLine: 'instant',
        servingSize: 'cup',
    },
    {
        dailyKcal: 1268,
        dailyPortion: 3.25,
        key: 'instant:cup:3.25',
        productLine: 'instant',
        servingSize: 'cup',
    },
    {
        dailyKcal: 1300,
        dailyPortion: 3.3333,
        key: 'instant:cup:3.3333',
        productLine: 'instant',
        servingSize: 'cup',
    },
    {
        dailyKcal: 1365,
        dailyPortion: 3.5,
        key: 'instant:cup:3.5',
        productLine: 'instant',
        servingSize: 'cup',
    },
    {
        dailyKcal: 1430,
        dailyPortion: 3.6667,
        key: 'instant:cup:3.6667',
        productLine: 'instant',
        servingSize: 'cup',
    },
    {
        dailyKcal: 1463,
        dailyPortion: 3.75,
        key: 'instant:cup:3.75',
        productLine: 'instant',
        servingSize: 'cup',
    },
    {
        dailyKcal: 1560,
        dailyPortion: 4,
        key: 'instant:cup:4',
        productLine: 'instant',
        servingSize: 'cup',
    },
    {
        dailyKcal: 1658,
        dailyPortion: 4.25,
        key: 'instant:cup:4.25',
        productLine: 'instant',
        servingSize: 'cup',
    },
    {
        dailyKcal: 1690,
        dailyPortion: 4.3333,
        key: 'instant:cup:4.3333',
        productLine: 'instant',
        servingSize: 'cup',
    },
    {
        dailyKcal: 1755,
        dailyPortion: 4.5,
        key: 'instant:cup:4.5',
        productLine: 'instant',
        servingSize: 'cup',
    },
    {
        dailyKcal: 1820,
        dailyPortion: 4.6667,
        key: 'instant:cup:4.6667',
        productLine: 'instant',
        servingSize: 'cup',
    },
    {
        dailyKcal: 1853,
        dailyPortion: 4.75,
        key: 'instant:cup:4.75',
        productLine: 'instant',
        servingSize: 'cup',
    },
    {
        dailyKcal: 1950,
        dailyPortion: 5,
        key: 'instant:cup:5',
        productLine: 'instant',
        servingSize: 'cup',
    },
    {
        dailyKcal: 2048,
        dailyPortion: 5.25,
        key: 'instant:cup:5.25',
        productLine: 'instant',
        servingSize: 'cup',
    },
    {
        dailyKcal: 2080,
        dailyPortion: 5.3333,
        key: 'instant:cup:5.3333',
        productLine: 'instant',
        servingSize: 'cup',
    },
    {
        dailyKcal: 2145,
        dailyPortion: 5.5,
        key: 'instant:cup:5.5',
        productLine: 'instant',
        servingSize: 'cup',
    },
    {
        dailyKcal: 2210,
        dailyPortion: 5.6667,
        key: 'instant:cup:5.6667',
        productLine: 'instant',
        servingSize: 'cup',
    },
    {
        dailyKcal: 2243,
        dailyPortion: 5.75,
        key: 'instant:cup:5.75',
        productLine: 'instant',
        servingSize: 'cup',
    },
    {
        dailyKcal: 2340,
        dailyPortion: 6,
        key: 'instant:cup:6',
        productLine: 'instant',
        servingSize: 'cup',
    },
    {
        dailyKcal: 2438,
        dailyPortion: 6.25,
        key: 'instant:cup:6.25',
        productLine: 'instant',
        servingSize: 'cup',
    },
    {
        dailyKcal: 2470,
        dailyPortion: 6.3333,
        key: 'instant:cup:6.3333',
        productLine: 'instant',
        servingSize: 'cup',
    },
    {
        dailyKcal: 2535,
        dailyPortion: 6.5,
        key: 'instant:cup:6.5',
        productLine: 'instant',
        servingSize: 'cup',
    },
    {
        dailyKcal: 2600,
        dailyPortion: 6.6667,
        key: 'instant:cup:6.6667',
        productLine: 'instant',
        servingSize: 'cup',
    },
    {
        dailyKcal: 2633,
        dailyPortion: 6.75,
        key: 'instant:cup:6.75',
        productLine: 'instant',
        servingSize: 'cup',
    },
    {
        dailyKcal: 2730,
        dailyPortion: 7,
        key: 'instant:cup:7',
        productLine: 'instant',
        servingSize: 'cup',
    },
    {
        dailyKcal: 2828,
        dailyPortion: 7.25,
        key: 'instant:cup:7.25',
        productLine: 'instant',
        servingSize: 'cup',
    },
    {
        dailyKcal: 2860,
        dailyPortion: 7.3333,
        key: 'instant:cup:7.3333',
        productLine: 'instant',
        servingSize: 'cup',
    },
    {
        dailyKcal: 2925,
        dailyPortion: 7.5,
        key: 'instant:cup:7.5',
        productLine: 'instant',
        servingSize: 'cup',
    },
    {
        dailyKcal: 2990,
        dailyPortion: 7.6667,
        key: 'instant:cup:7.6667',
        productLine: 'instant',
        servingSize: 'cup',
    },
    {
        dailyKcal: 3023,
        dailyPortion: 7.75,
        key: 'instant:cup:7.75',
        productLine: 'instant',
        servingSize: 'cup',
    },
    {
        dailyKcal: 3120,
        dailyPortion: 8,
        key: 'instant:cup:8',
        productLine: 'instant',
        servingSize: 'cup',
    },
    {
        dailyKcal: 3218,
        dailyPortion: 8.25,
        key: 'instant:cup:8.25',
        productLine: 'instant',
        servingSize: 'cup',
    },
];
